#!/bin/bash
for i in $(seq 1 20); do
    mkdir -p "$i"    
    echo "$i" > "$i/$i.txt"
    ln -s "$i/$i.txt" "./$i.txt"
done
for i in $(seq 1 20); do    
	if ! grep -q "4" "$i/$i.txt"; then
        rm "$i/$i.txt"        
        rm "./$i.txt" 
	fi
done
echo "Новое содержимое для 14/14.txt" > "14/14.txt"
